# Generated by Django 4.1.7 on 2023-03-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="email",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="email",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
