# Generated by Django 4.1.7 on 2023-03-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_business_email_alter_jobseeker_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="upload_companyphoto",
            field=models.ImageField(upload_to="images/companyphoto"),
        ),
        migrations.AlterField(
            model_name="business",
            name="upload_photo",
            field=models.ImageField(upload_to="images/photo"),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="upload_photo",
            field=models.ImageField(upload_to="images/photo"),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="upload_resume",
            field=models.ImageField(upload_to="images/resume"),
        ),
    ]
